# Generated by Django 4.2.7 on 2023-11-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
