# Generated by Django 4.2.7 on 2023-11-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='allergies',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='diagnosis',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='medications',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='surgeries',
            field=models.CharField(max_length=30),
        ),
    ]
