# Generated by Django 4.2.7 on 2023-11-29 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_medicalhistory_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
