# Generated by Django 4.2.7 on 2023-11-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_medicalhistory_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.TextField(max_length=30),
        ),
    ]
